apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sw49jkv14-nodejs 
  janus-idp.io/tekton: sw49jkv14-nodejs
  backstage.io/kubernetes-id: sw49jkv14-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sw49jkv14-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml